# Сколько опыта нужно, чтобы создать одну бутылочку
exp-cost: 10
# Забирать ли пустую бутылку после получения пузырька с опытом
remove-bottle: true
# Задержка использования пузырька опыта после создания, для предотвращения случайного использования. Количество тиков
exp-use-cooldown: 10